### ISSUE TITLE
Building New Sedimentation Tank for Contact Chamber experiments

### ISSUE THREAD

**Issue by YeonjinYun** [AguaClara/contact_chamber#10]
During the meeting with Monroe, we decided to try to make a smaller and shorter sedimentation tank for our experiment. Since we have such a low concentration of clay, it takes too much time to actually form a floc blanket. So Monroe suggested that maybe creating a new sedimentation tank will help forming a floc blanket.

**Comment by cheertsang** [comment]
What dimensions should the new sedimentation tube be? How will decreasing the dimensions allow the floc blanket to form faster?

**Comment by TanviNaidu** [comment]
Might be useful talking to the folks at High Rate Sed, they might have some mathCad/python code for sed tank design!

**Comment by TanviNaidu** [comment]
@MikeZarecor Do you have any recommendations?

**Comment by MikeZarecor** [comment]
We actually don't have any code for sed-tank design yet, we are still using the sed tank from last semester which was built based on hand calcs. 

Section 2.4 from the HRS Fall 2017 Final Report should be useful for designing the tank (see link below). Let me know if you need a hand with design or fabrication. I believe Chris Galantino did the calcs for the last design, so he may be a useful resource as well. 

https://drive.google.com/file/d/1gbIfs6kDCJmKAiMyvt0MOeTQabgSxkDj/view?usp=sharing

**Comment by cheertsang** [comment]
A sedimentation tube redesign is no longer necessary because we will not be using the sedimentation tube anymore. We will be measuring headloss across the flocculator instead to figure out whether or not the contact chamber will help reduce headloss in the flocculator.
