### ISSUE TITLE
Changes in experimental apparatus after Symposium

### ISSUE THREAD

**Issue by YeonjinYun** [AguaClara/contact_chamber#11]
1. The team decided to have influent turbidity of 100, not 10.
2. Our main goal measurement will be headloss before and after the flocculator instead of comparing the influent and effluent turbidity, since the optimal use of contact chamber is decreasing the amount of coagulant sticking on to the walls of flocculator causing headloss.
3. We do not really have to change the dimensions of sedimentation tank, or we actually don't need sedimentation tank in our design at all. (effluent turbidimeter as well)
4. Focus more on the contact chamber design to reduce the headloss as much as we can. Does the contact chamber do actually help reducing the headloss in flocculator? Do another red-dye test to observe the fluid dynamics with new input values. (May need to calculate viscosity and density of the coagulant dose, since it is more concentrated than before)
5. Rinse the system everytime we end one experiment.

**Comment by cheertsang** [comment]
March 17, 2018

Redesigned experiment for 100 NTU influent turbidity.
- **Removed sedimentation tube**, connected outflow from flocculator directly to waste drain
- Changed **clay stock concentration to 2 g/L**, may need to reduce to ~1.5 g/L; PID is having a hard time keeping the influent turbidity at 100 NTU, fluctuates between 70-120 NTU
- Changed **coagulant stock to 0.0567 g/L**, run at 20 RPM (calculated using [HRS Dosing](https://github.com/AguaClara/high_rate_sedimentation/blob/master/PAC%20Dosing.md))

**Comments/Questions:**

The contact chamber is currently in the downflow orientation, where water and coagulant enter from the top and flow out the bottom, but I think using the contact chamber in the **upflow orientation**, with water and coagulant entering the contact chamber from the bottom makes the most sense. The reasoning behind this is that increasing residence time in the contact chamber would most likely increase the chances that coagulant particles will collide with clay particles. 

How should we go about cleaning the flocculator in between trials to ensure coagulant removal for accurate comparisons? 

Would it be helpful to keep the sedimentation tube to collect data on effluent turbidity even though we are using headloss to gauge contact chamber efficiency?

**Comment by monroews** [comment]
If PID is resulting in fluctuations, then try changing I in PID. Increase it (by a factor of 2) and decrease it by a factor of 2 and see if either is better. If that doesn't fix the problem, then decrease P by a factor of 2. Obviously, if making a change improves it, but doesn't fix it, then make an additional change.

You can clean the flocculator by running a bubble of air through the flocculator. You can probably do this by tilting the accumulator chamber so that a bit of air escapes into the effluent line.

**Comment by YeonjinYun** [comment]
Mar. 19th.
Changed P to 250m from 500m, I to 500m from 250m, 7kPa pressure difference to cm,
Concentration of clay 2g/L, 0.8mL 70.9/L PACI per L (decided to keep clay concentration even though it might be little too concentrated for PID control, because we want to run longer experiments, and if the stock is dilute, solutions will run out quicker)
Running ~24 hours experiment!

**Comment by cheertsang** [comment]
Added a pressure sensor across flocculator to measure headloss.
