### ISSUE TITLE
Sequence of experiments following changes after symposium

### ISSUE THREAD

**Issue by cheertsang** [AguaClara/contact_chamber#14]
March 23, 2018

Run trials with contact chamber in downflow orientation (24 hour experiments)
- March 23: ran water at 600 RPM to clean out flocculator, allowed contact chamber to fill up
- March 24
- March 25

Run trials without contact chamber 
- March 26
- March 27
- March 28

Run trials with contact chamber in upflow orientation

Things to remember for each trial:
- clean out flocculator between trials (Run water at maximum speed: 600 RPM)
- clean out influent turbidimeter

**Comment by cheertsang** [comment]
March 24: 
- contact chamber in downflow orientation
- cleaned out flocculator with water pump at 600 RPM
- refilled clay and stock solutions
- started new trial - compare results to see if 600 RPM water is effectively cleaning out flocculator (6 PM)

**Comment by YeonjinYun** [comment]
March 25:

- Contact chamber in downflow orientation
- Cleaned out flocculator with water pump at 600 RPM
- Refilled clay and stock solutions
- Started new trial from 6:00PM

**Comment by canaandelgado** [comment]
March 26th (morning):

- Previous experiment finished... removal of contact chamber trails start
- Refilled clay stocks during experiment (4 g clay w/ 2L water)
- coagulant tank leaking (tried to fix, but not entirely sure if it will be efficient...)

**Comment by cheertsang** [comment]
Large pressure fluctuations across the flocculator due to the water pump; added flow accumulator to reduce amplitude of fluctuations.
