### ISSUE TITLE
RA meeting before or after spring break?

### ISSUE THREAD

**Issue by TanviNaidu** [AguaClara/contact_chamber#15]
Hi Team,

Its time for another RA meeting! This will be similar to the last one, mostly to check in and figure out where I can offer any assistance. 
Would you prefer for this to be before or after spring break? Please let me know some times that work for you guys!

**Comment by cheertsang** [comment]
Hi @TanviNaidu ! Would 4:30 PM this Wednesday (3/28) work for you?

**Comment by TanviNaidu** [comment]
Hey guys, 
4:30 doesn't work for me, any chance you'll be there at 4?

**Comment by cheertsang** [comment]
Hi Tanvi, sorry, 4 won't work. I guess we can schedule a meeting for after break.

**Comment by cheertsang** [comment]
Met with RA to discuss changes in experiment, adding flow accumulator
