### ISSUE TITLE
RA meeting

### ISSUE THREAD

**Issue by canaandelgado** [AguaClara/contact_chamber#16]
Today we met with our RA and discussed current setup and future work that we can do. We changed the design layout of our system (moved accumulator). We also worked on the problem we were experiencing with our pressure.

**Future questions**:

- do we need to clean out the tubing just running high velocity water through or should we implement a new mode to clean so that between new experiments we have no flawed results

- compare sizing of the different contact chambers (why did the bigger one work better)

- add results from Contact Chamber 2017 Spring not GitHub to inquire on results

- running trails with just coagulant and ones with clay and coagulant to see how headless was calculated

**Comment by canaandelgado** [comment]
coagulant loss to walls with flocculator and contact chamber was something investigated in previous semesters as well

**Comment by cheertsang** [comment]
- We decided to run high velocity water and air bubbles to clean out flocculator
- We are hypothesizing that the two different sizes of contact chambers will have similar results, as long as the length is the same. 
- We looked at the Contact Chamber results from previous semesters; they were successful in reducing headloss across the flocculator using the contact chamber.
