### ISSUE TITLE
Meeting with Monroe

### ISSUE THREAD

**Issue by YeonjinYun** [AguaClara/contact_chamber#3]
First Meeting: 4:30-5:30 PM February 15th, 2018

**Comment by YeonjinYun** [comment]
Calculate the residence time in the contact chamber -> 127 seconds
Maybe longer residence time in the contact chamber? How? Change the dimension! (bigger radius or longer tube)
Calculate coagulant dose and change it to 1.00mg/L and check the effluent turbidity, if the turbidity is higher, then change the coagulant dose to find the ideal dose
Compare results without waiting for floc blanket to form
Therefore, make a sedimentation tank smaller version to speed up the process of forming floc blanket

**Comment by cheertsang** [comment]
Removed sedimentation tank, changed influent turbidity to 100 NTU
