### ISSUE TITLE
Research on new Contact Chamber Dimensions

### ISSUE THREAD

**Issue by YeonjinYun** [AguaClara/contact_chamber#4]
We need to improve on our contact chamber dimensions, since the previous semester's contact chamber was designed based on the turbulent jet. However, it was proven by the red-dye test that turbulent jet did not occur in the contact chamber. Therefore, we need to change the dimensions to improve the performance of the contact chamber, which means improving the mixing process of coagulant and clay particles.

**Comment by cheertsang** [comment]
We will test both contact chambers using a measure of headloss to determine which is more efficient at 100 NTU.
