### ISSUE TITLE
Red-dye test

### ISSUE THREAD

**Issue by YeonjinYun** [AguaClara/contact_chamber#5]
To observe the fluid dynamics of coagulant dose (red-dye added) in the contact chamber

**Comment by cheertsang** [comment]
Video of red-dye test.
[Red-dye test with upflow orientation](https://drive.google.com/open?id=131jMKlmVd9_bHArfwS7RPK_GzQaNJrif)

**Comment by YeonjinYun** [comment]
From the Red-dye test, we could conclude that there was definitely no turbulent jet occurring in our contact chamber. Therefore, next thing we will try is to flip the contact chamber and re-do the red-dye test and observe the new fluid dynamics from that.

**Comment by monroews** [comment]
Post the photo of the dye test here.

**Comment by cheertsang** [comment]
Video of red-dye test.
[Red-dye test with downflow orientation](https://drive.google.com/file/d/1asHUX6URb8W46GxIXgSc_ehq2-tJlSVi/view?usp=sharing)

**Comment by cheertsang** [comment]
Red dye test showed upflow orientation had more residence time and better mixing, but downflow orientation had less contact with the contact chamber walls, which may reduce the amount of coagulant sticking to the walls. We will stick with the upflow orientation for purposes of comparing the old and new contact chambers.
