### ISSUE TITLE
Experiments

### ISSUE THREAD

**Issue by YeonjinYun** [AguaClara/contact_chamber#6]
February 15th, 2018
Experiment with flipped contact chamber with 76 rpm water, 20 rpm coagulant for 15 minutes

**Comment by cheertsang** [comment]
February 24, 2018
Added 7 kPa pressure sensor.
Experiment design:

- contact chamber with down-flow orientation
- 76 rpm water pump
- 20 rpm coagulant
- waited for influent turbidity to reach 10 NTU 
- Start time: 1:07 PM 
- End time: 1:54 PM

**Comment by YeonjinYun** [comment]
February 26, 2018
Keep 7kPa pressure sensor
Experiment design:

contact chamber with down-flow orientation
76 rpm water pump
20 rpm coagulant
waited for influent turbidity to reach 10 NTU
Start time: 6:50 PM
End time: 12:30 AM

**Comment by YeonjinYun** [comment]
Added Coagulant stock 0.25ml of 70.9g/L PACL with 500mL of water

**Comment by YeonjinYun** [comment]
Added Clay stock 0.4g of clay with 1L of water

**Comment by YeonjinYun** [comment]
Qualitative Analysis on February 26th experiment:
After 6 hours of experiment, there are big flocs floating around in the sedimentation tube, however, I have seen a lot of flocs sticking to the wall of sedimentation tube, not sliding down. Also, since there is 1 rpm connected to the weir, the flocs are stuck in the waste stream since there is not enough pressure to push it out of effluent stream. But definitely see a lot of flocs have formed, but they are not forming floc blanket as we have expected. This is different result from last semester where we haven't changed anything except the contact chamber orientation. Also, the effluent turbidity doesn't seem to go down with longer experiments, which suggests that we have problem in our apparatus. 
Tanvi suggested that we might want to wash the sedimentation tank and that will be the next thing our team will try and as Monroe suggested, we will make a smaller version of sedimentation tank for our experiment to shorten the time taken to form floc blanket.

**Comment by YeonjinYun** [comment]
![1125x1500 jpeg 60e3fe2b7575475997a0e3eb26ff08d0](https://user-images.githubusercontent.com/35943903/36939591-63931508-1f01-11e8-8e34-4a94b82cfa11.jpg)
I have seen the flocs or big coagulant clumps sticking to the walls of the sedimentation tank. This suggests that we might be using too high coagulant dose.

**Comment by YeonjinYun** [comment]
![1125x1500 jpeg 2044f718040c461b988ceb903392af28](https://user-images.githubusercontent.com/35943903/36939604-94e56cfa-1f01-11e8-9d03-eb655f6d6093.jpg)
After the 1 rpm pump attached to the weir, it seems like we don't have enough flow to flush the flocs out as effluent.

**Comment by YeonjinYun** [comment]
![1125x1500 jpeg a0a18d7f07a74c6aa9901a20937b970a](https://user-images.githubusercontent.com/35943903/36939610-b90b5216-1f01-11e8-962b-5743f10d8492.jpg)
We thought that there was no floc blanket formed in our sedimentation tank, however when I was washing the system with high flow rate water, a lot of flocs have came out, does this mean we had the floc blanket that has been sunk in the bottom part?

**Comment by cheertsang** [comment]
We won't be using a sedimentation tank anymore. Instead, we will be measuring the efficiency of the contact chamber using headloss.
