### ISSUE TITLE
RA Meeting

### ISSUE THREAD

**Issue by cheertsang** [AguaClara/contact_chamber#9]
Some suggestions:
- run an experiment overnight (>12 hrs) to generate floc blanket
- see how long it takes to generate floc blanket
- clean out algal growth in flocculator

Standardize experimental variables: 
- run high velocity water through flocculator to clean it out in between experiments
- clean out sedimentation tube between experiments
- re-generate floc blanket for each experiment
- since this will take a long time given the low starting turbidity, find a way to shorten floc blanket generation time

Possible ways to reduce time it takes to generate floc blanket:
- fabricate shorter sedimentation tube
- use high concentrations of clay/coagulant at start of experiment to generate floc blanket, then run experiment as normal

Future experiments procedure:
1. with contact chamber
- down-flow orientation
- water pump at 76 rpm, coagulant at 20 rpm (plant concentration of ~1.6 mg/L)

*clean out flocculator with high velocity water, set water pump RMP very high?
*drain sedimentation tube fully

2. without contact chamber

**Comment by cheertsang** [comment]
March 3, 2018

[Recalculate coagulant stock concentration](https://github.com/AguaClara/contact_chamber/blob/master/code/Clay_Coagulant_Concentration.md)
We ideally want the concentration of coagulant throughout the plant to be 1.5 mg/L. So, recalculating the coagulant stock concentration, we should start with a stock concentration of 54 mg/L, which is 3.8 mL of 70.9 g/L PACl solution in 5 L of water.

**Comment by TanviNaidu** [comment]
The High G floc and HRS teams have coagulant concentration through the plant set as between 1.4 and 1.6 mg/L, if I remember correctly. 
It might be helpful for standardizing results if your team chooses a concentration value closer to these as well!

**Comment by TanviNaidu** [comment]
Could you please remind me what your current coagulant concentration through the plant is set as?

**Comment by cheertsang** [comment]
Our current coagulant concentration is 3.94 mg/L throughout the plant, so our stock solution is 54 mg/L, while running the pump at 20 RPM. We had it set this high because we were trying to reduce the influent turbidity of 10 NTU to 2 NTU at the effluent, but with such a low turbidity at the influent, the coagulant was not sticking to the clay. We found that 3.94 mg/L reduced our effluent turbidity to around 3 NTU.

**Comment by cheertsang** [comment]
Shouldn't we have a lower coagulant concentration throughout the plant than HRS and High G, since we are starting with an influent of 10 NTU rather than 100 NTU?

**Comment by cheertsang** [comment]
In order to shorten experiment time, we are removing the sed tank and instead using headloss as a measure of efficiency.
